version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"  # Expose Angular at /llm-wordgame/
    depends_on:
      - backend
    networks:
      - ollama-docker

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    expose:
      - "5001"
    environment:
      - OLLAMA_API=http://ollama:11434
    depends_on:
      - ollama
    networks:
      - ollama-docker

  ollama:
    image: ollama/ollama
    volumes:
      - ollama_data:/root/.ollama
    expose:
      - "11434"
    restart: unless-stopped
    command: serve
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    networks:
      - ollama-docker
   

    

  # nginx:
  #   image: nginx:alpine
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #     - ./dist/demo/browser:/usr/share/nginx/html
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - frontend
  #     - backend

volumes:
  ollama_data:
networks:
  ollama-docker:
    external: false