version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"  # Expose Angular at /llm-wordgame/
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    expose:
      - "5001"

  # nginx:
  #   image: nginx:alpine
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #     - ./dist/demo/browser:/usr/share/nginx/html
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - frontend
  #     - backend