version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"  # Expose Angular at /llm-wordgame/
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    expose:
      - "5001"
    environment:
      - OLLAMA_API=http://ollama:11434
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped

  # nginx:
  #   image: nginx:alpine
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #     - ./dist/demo/browser:/usr/share/nginx/html
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - frontend
  #     - backend

volumes:
  ollama_data: